In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../../datasets/sales.csv")
df.head()

,order_id,region,country,product,quantity,price,order_date,customer_id
0,1,North America,USA,Laptop,2,899.99,2024-01-10,1.0
1,2,Europe,Germany,Phone,5,499.99,2024-01-12,2.0
2,3,Asia,India,Tablet,3,299.99,2024-01-15,3.0
3,4,North America,Canada,Monitor,4,199.99,2024-01-18,NaN
4,5,Europe,France,Laptop,1,999.99,2024-01-20,4.0

In [5]:
df.isnull().sum()

order_id       0
region         0
country        0
product        0
quantity       0
price          0
order_date     0
customer_id    1
dtype: int64

In [6]:
df_clean=df.dropna()
df_clean.head()

,order_id,region,country,product,quantity,price,order_date,customer_id
0,1,North America,USA,Laptop,2,899.99,2024-01-10,1.0
1,2,Europe,Germany,Phone,5,499.99,2024-01-12,2.0
2,3,Asia,India,Tablet,3,299.99,2024-01-15,3.0
4,5,Europe,France,Laptop,1,999.99,2024-01-20,4.0
5,6,Asia,Japan,Phone,6,699.99,2024-01-22,5.0