## 📘 Week 3 – Day 4: Pandas Basics
Today we begin exploring Pandas, the most essential Python library for data engineering.

### Learning Goals
Understand DataFrames, rows, columns
Load CSV files using pandas
Select columns & filter rows
Add new computed columns
Sort, group, and aggregate data
Join/Merge datasets

In [2]:
import pandas as pd

# Load dataset
df = pd.read_csv("../../datasets/sales.csv")

df.head()

,order_id,region,country,product,quantity,price,order_date,customer_id
0,1,North America,USA,Laptop,2,899.99,2024-01-10,1.0
1,2,Europe,Germany,Phone,5,499.99,2024-01-12,2.0
2,3,Asia,India,Tablet,3,299.99,2024-01-15,3.0
3,4,North America,Canada,Monitor,4,199.99,2024-01-18,NaN
4,5,Europe,France,Laptop,1,999.99,2024-01-20,4.0

## Basic Data Exploration Functions

| Command | Purpose |
|--------|---------|
| `df.head()` | First 5 rows |
| `df.describe()` | Summary statistics |
| `df.info()` | Data types + null counts |
| `df.shape` | Rows, columns |
| `df.dtypes` | Data types of each column |

In [4]:
print(df.head())

   order_id         region  country  product  quantity   price  order_date  \
0         1  North America      USA   Laptop         2  899.99  2024-01-10
1         2         Europe  Germany    Phone         5  499.99  2024-01-12
2         3           Asia    India   Tablet         3  299.99  2024-01-15
3         4  North America   Canada  Monitor         4  199.99  2024-01-18
4         5         Europe   France   Laptop         1  999.99  2024-01-20

   customer_id
0          1.0
1          2.0
2          3.0
3          NaN
4          4.0

In [5]:
print(df.describe())

       order_id  quantity       price  customer_id
count   8.00000  8.000000    8.000000     7.000000
mean    4.50000  3.375000  512.490000     2.571429
std     2.44949  1.685018  318.198052     1.511858
min     1.00000  1.000000  199.990000     1.000000
25%     2.75000  2.000000  274.990000     1.500000
50%     4.50000  3.500000  399.990000     2.000000
75%     6.25000  4.250000  749.990000     3.500000
max     8.00000  6.000000  999.990000     5.000000

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     8 non-null      int64
 1   region       8 non-null      object
 2   country      8 non-null      object
 3   product      8 non-null      object
 4   quantity     8 non-null      int64
 5   price        8 non-null      float64
 6   order_date   8 non-null      object
 7   customer_id  7 non-null      float64
dtypes: float64(2), int64(2), object(4)
memory usage: 644.0+ bytes
None

In [7]:
print(df.shape)

(8, 8)

In [8]:
print(df.dtypes)

order_id         int64
region          object
country         object
product         object
quantity         int64
price          float64
order_date      object
customer_id    float64
dtype: object

#### Selecting Columns in Pandas
- Single column: `df["product"]`  
- Multiple columns: `df[["product", "price", "quantity"]]`  
- Invalid: `df["product", "price"]`

In [3]:
df["product"]

0     Laptop
1      Phone
2     Tablet
3    Monitor
4     Laptop
5      Phone
6    Monitor
7     Tablet
Name: product, dtype: object

In [5]:
df[["product", "price", "quantity"]]

   product   price  quantity
0   Laptop  899.99         2
1    Phone  499.99         5
2   Tablet  299.99         3
3  Monitor  199.99         4
4   Laptop  999.99         1
5    Phone  699.99         6
6  Monitor  199.99         2
7   Tablet  299.99         4

In [6]:
df["product", "price"]

KeyError: ('product', 'price')

#### Filtering Rows
Examples:
-- `df[df["quantity"] >3]`
-- `df[df["product"] == "Laptop"]`
-- Combined filters:`df[(df["region"] == "Europe") & (df["price"] >500)]`

In [7]:


df[df["quantity"] > 3]

,order_id,region,country,product,quantity,price,order_date,customer_id
1,2,Europe,Germany,Phone,5,499.99,2024-01-12,2.0
3,4,North America,Canada,Monitor,4,199.99,2024-01-18,NaN
5,6,Asia,Japan,Phone,6,699.99,2024-01-22,5.0
7,8,North America,USA,Tablet,4,299.99,2024-01-25,1.0

In [32]:
df[df["product"] == "Laptop"]

,order_id,region,country,product,quantity,price,order_date,customer_id
0,1,North America,USA,Laptop,2,899.99,2024-01-10,1.0
4,5,Europe,France,Laptop,1,999.99,2024-01-20,4.0

In [34]:
df[(df["region"] == "Europe") & (df["price"] >500)]

   order_id  region country product  quantity   price  order_date  customer_id
4         5  Europe  France  Laptop         1  999.99  2024-01-20          4.0

####  Handling Missing Values
-- Find missing values:`df.isnull().sum()`
-- Filter rows with nulls:`df[df["customer_id"].isnull()]`

In [8]:
df.isnull().sum()

order_id       0
region         0
country        0
product        0
quantity       0
price          0
order_date     0
customer_id    1
dtype: int64

In [10]:
df[df["customer_id"].isnull()]

,order_id,region,country,product,quantity,price,order_date,customer_id
3,4,North America,Canada,Monitor,4,199.99,2024-01-18,NaN

#### + Adding Computed Columns
Example: Total sales amount
`df["Amount"] = df["price"] * df["quantity"]`

In [11]:
df["Amount"] = df["price"] * df["quantity"]
df.head()

,order_id,region,country,product,quantity,price,order_date,customer_id,Amount
0,1,North America,USA,Laptop,2,899.99,2024-01-10,1.0,1799.98
1,2,Europe,Germany,Phone,5,499.99,2024-01-12,2.0,2499.95
2,3,Asia,India,Tablet,3,299.99,2024-01-15,3.0,899.97
3,4,North America,Canada,Monitor,4,199.99,2024-01-18,NaN,799.96
4,5,Europe,France,Laptop,1,999.99,2024-01-20,4.0,999.99

#### Sorting Data
-- `df.sort_values("Amount", ascending=False)
-- `df.sort_values("Amount", ascending=True)

In [12]:
df.sort_values("Amount", ascending=False).head(3)

,order_id,region,country,product,quantity,price,order_date,customer_id,Amount
5,6,Asia,Japan,Phone,6,699.99,2024-01-22,5.0,4199.94
1,2,Europe,Germany,Phone,5,499.99,2024-01-12,2.0,2499.95
0,1,North America,USA,Laptop,2,899.99,2024-01-10,1.0,1799.98

In [13]:
df.sort_values("Amount", ascending=True).head(5)

,order_id,region,country,product,quantity,price,order_date,customer_id,Amount
6,7,Europe,Germany,Monitor,2,199.99,2024-01-23,2.0,399.98
3,4,North America,Canada,Monitor,4,199.99,2024-01-18,NaN,799.96
2,3,Asia,India,Tablet,3,299.99,2024-01-15,3.0,899.97
4,5,Europe,France,Laptop,1,999.99,2024-01-20,4.0,999.99
7,8,North America,USA,Tablet,4,299.99,2024-01-25,1.0,1199.96

### GroupBy (Aggregations)

Examples:

- Total Amount by region  
  `df.groupby("region")["Amount"].sum()`

- Count orders by product  
  `df.groupby("product")["order_id"].count()`

- Avg quantity by region  
  `df.groupby("region")["quantity"].mean()`

- Max amount by product  
  `df.groupby("product")["Amount"].max()`

In [14]:
df.groupby("region")["Amount"].sum()

region
Asia             5099.91
Europe           3899.92
North America    3799.90
Name: Amount, dtype: float64

In [15]:
df.groupby("product")["order_id"].count()

product
Laptop     2
Monitor    2
Phone      2
Tablet     2
Name: order_id, dtype: int64

In [16]:
df.groupby("region")["quantity"].mean()

region
Asia             4.500000
Europe           2.666667
North America    3.333333
Name: quantity, dtype: float64

In [17]:
df.groupby("product")["Amount"].max()

product
Laptop     1799.98
Monitor     799.96
Phone      4199.94
Tablet     1199.96
Name: Amount, dtype: float64

### Joining Two CSV Files

Steps:
1. Load sales.csv  
2. Load customers.csv  
3. Merge on `customer_id` using LEFT JOIN

In [21]:
import pandas as pd
df_sales=pd.read_csv("../../datasets/sales.csv")
df_customers=pd.read_csv("../../datasets/customers.csv")
df_sales["Amount"]=df_sales["price"] * df_sales["quantity"]                         
df_merged=df_sales.merge(df_customers, on="customer_id",how="left") 
df_merged.head()

,order_id,region,country_x,product,quantity,price,order_date,customer_id,Amount,first_name,last_name,country_y,loyalty_points
0,1,North America,USA,Laptop,2,899.99,2024-01-10,1.0,1799.98,Robert,King,USA,350.0
1,2,Europe,Germany,Phone,5,499.99,2024-01-12,2.0,2499.95,Linda,Schneider,Germany,420.0
2,3,Asia,India,Tablet,3,299.99,2024-01-15,3.0,899.97,Rajesh,Kumar,India,290.0
3,4,North America,Canada,Monitor,4,199.99,2024-01-18,NaN,799.96,NaN,NaN,NaN,NaN
4,5,Europe,France,Laptop,1,999.99,2024-01-20,4.0,999.99,Marie,Dupont,France,500.0

### Highest Value Order (Top 1)

In [22]:
df_merged.sort_values("Amount", ascending=False).head(1)

,order_id,region,country_x,product,quantity,price,order_date,customer_id,Amount,first_name,last_name,country_y,loyalty_points
5,6,Asia,Japan,Phone,6,699.99,2024-01-22,5.0,4199.94,Hiroshi,Tanaka,Japan,410.0